### ISSUE TITLE
Tests are failing due to changes in Travis

### ISSUE THREAD

**Issue by dfeldman** [spiffe/spire-examples#35]
Travis CI seems to be giving us a 1-core instance now instead of 2-core, and 2 cores are required to run Minikube so all the Kubernetes tests fail. We should either figure out how to make Travis work, switch to a different build system, or not run Kubernetes tests for this repo.

**Comment by Andres-GC** [comment]
Hi @dfeldman 
The test are passing again. I think we can close this issue. Are you Ok with that?
Regards.

**Comment by dfeldman** [comment]
You're right! Closing
